package casper.asset
/**
 * 	Its file generated by assets.py
 */
import casper.signal.concrete.*
import casper.signal.util.EitherCollection

fun createAssetsArrayLoader(manager: AssetManager): EitherFuture<Assets, String> {
	val result = EitherSignal<Assets, String>()
	val collection = EitherCollection()
LOADERS_LIST
	val future = collection.future()
	future.then({
		try {
			val assets = Assets(manager)
			result.accept(assets)
		}
		catch (t:Throwable) {
			result.reject(t.toString())
		}
	}, {
		result.reject(it.joinToString("\n\n"))
	})
	return result
}

class Assets(manager: AssetManager) {
ASSETS_LIST
}

