package casper.asset
/**
 * 	Its file generated by assets.py
 */
import casper.signal.Promise
import casper.signal.PromiseSignal
import casper.signal.PromiseUnion

fun createAssetsArrayLoader(manager: AssetManager): Promise<Assets, String> {
	val result = PromiseSignal<Assets, String>()
	PromiseUnion(
LOADERS_LIST
	).then({
		try {
			val assets = Assets(manager)
			result.accept(assets)
		}
		catch (t:Throwable) {
			result.reject(t.toString())
		}
	}, {
		result.reject(it.joinToString("\n\n"))
	})
	return result
}

class Assets(manager: AssetManager) {
ASSETS_LIST
}

